### ISSUE TITLE
Map is not updated in visualization of simulator

### ISSUE THREAD

**Issue by rmbeumer** [tue-robotics/emc_simulator#43]
![image](https://user-images.githubusercontent.com/36734416/224654174-7ee78cb1-5203-4ab9-91d5-acec70b4b4f5.png)

The visualization of the LRF data seems to be according to the desired map, but the map displayed is the default map.
The problem should be reproducible when starting the simulator with another map than the default one (mrc-sim --map *path/to/other_map*) and then visualizing it (mrc-viz).

**Comment by ThijsBeurskensTUE** [comment]
rviz uses the map server to get the map data, which in turn uses a yaml file to specify the image path, resolution and other settings. A possible fix is to feed this yaml file to the simulator and get the image path from there.

**Comment by PetervDooren** [comment]
What we discussed with @ThijsBeurskensTUE was to make the simulator such that it reads the map data from the map_server. This way the two are always aligned. 
So TODO are two things:

1. make the simulator listen to the map published by the map server and use that to configure the simulated world
2. change the simulator script to take the yaml as parameter.

**Comment by PetervDooren** [comment]
https://github.com/tue-robotics/emc_simulator/pull/45 will take care of point 1. Although not all parameters from the yaml are used. mainly the origin of the map.
