### ISSUE TITLE
Not all map metadata is used in the simulator

### ISSUE THREAD

**Issue by PetervDooren** [tue-robotics/emc_simulator#46]
The simulator reads the map info from the map server as of #45 however not all info is taken into account. Only resolution is taken into account.
What still needs to be accounted for is:

- [ ] origin: either by transforming the shape in the internal representation or by transforming all pose estimates published by the simulator. !no, this must by the former since we want the coordinates of objects in the config.json to match what is defined here.
- [ ] occupied_thresh, free_thresh and negate: these may be used in determining what counts as wall or free space or door. But these are less important

**Comment by MatthijsBurgh** [comment]
Resolution is hardcoded see:
https://github.com/tue-robotics/emc_simulator/blob/0a35d35890de9b8a6aed1c124d2478c552545611/src/heightmap.cpp#L223
